### PR TITLE
Declare Python package and expose some API

### PR DESCRIPTION
**Pull request by McSinyx**
The tool has been working nicely for me so far, hence some polishing here so it's easier to be used as a dependency.

Breaking changes:
- Invocation is now `python3 -m pacfix` (or simply `pacfix`) instead of pointing Python to the source file.  For incremental development, `pip install -e ./` should work.
- CLI error messages differs slightly.
- Python ≥ 3.9 (available from Ubuntu 20.04 and above) is required for [PEP 585](https://peps.python.org/pep-0585), e.g. `list[int]`.  In reality I'm just too lazy to track down the minimum supported version otherwise.

I roughly filled `pyproject.toml`, most metadata there might need correction.  In addition, I would like to incorporate my modifications under a free software license, preferably copyleft.  Please don't merge as-is since the licensing would default to _all rights reserved_ and not very useful.

The changes are split into (IMHO) reasonably self-contained commits.  I wish I could submit them in separate PRs but they touch the same set of files.  The diffs should be clearer when review on a commit-by-commit basis.

### CODE REVIEW

**Comment by McSinyx** [comment]
Thanks for the merge!

**Comment by McSinyx** [comment]
BTW could you please tag the commit
corresponding to the release published on PyPI?

**Comment by hsh814** [comment]
I'v added a tag v0.0.1

**Comment by McSinyx** [comment]
Thanks!

**Pull request merged**
